# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('City', models.CharField(max_length=64)),
                ('Year', models.PositiveSmallIntegerField()),
                ('Base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.Base')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.TextField()),
                ('Cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Country', models.CharField(max_length=64)),
                ('GameLevel', models.CharField(max_length=64)),
                ('CountStart', models.IntegerField(max_length=2)),
                ('CountFinish', models.IntegerField(max_length=2)),
                ('Salary', models.PositiveSmallIntegerField()),
                ('Order', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Opposing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=64)),
                ('Country', models.CharField(max_length=64)),
                ('Coach', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('YearFact', models.PositiveSmallIntegerField()),
                ('Photo', models.ImageField(null=True, upload_to='')),
                ('Contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.Position'),
        ),
        migrations.AddField(
            model_name='club',
            name='Head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.Head'),
        ),
        migrations.AddField(
            model_name='club',
            name='League',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.League'),
        ),
        migrations.AddField(
            model_name='club',
            name='Matches',
            field=models.ManyToManyField(to='Football.Match'),
        ),
        migrations.AddField(
            model_name='club',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.Player'),
        ),
    ]
