# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='CountFinish',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='CountStart',
            field=models.IntegerField(),
        ),
    ]
