# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0002_auto_20170411_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Club', models.CharField(max_length=64, verbose_name='Название клуба')),
                ('City', models.CharField(max_length=64, verbose_name='Город размещения клуба')),
                ('Base', models.CharField(max_length=64, verbose_name='Тренировочная база')),
                ('Year', models.PositiveSmallIntegerField(verbose_name='Год создания клуба')),
                ('League', models.CharField(max_length=64, verbose_name='Принадлежность к лиге')),
                ('FIO', models.CharField(max_length=256, verbose_name='ФИО руководителя клуба')),
                ('Phone', models.CharField(max_length=13, verbose_name='Телефон руководителя клуба')),
                ('FIOGamer', models.CharField(max_length=256, verbose_name='ФИО игрока')),
                ('Position', models.CharField(max_length=20, verbose_name='Положение игрока в команде')),
                ('Birthday', models.DateField(verbose_name='Дата рождения')),
                ('YearFact', models.PositiveSmallIntegerField(verbose_name='Принят в команду(год)')),
                ('Photo', models.ImageField(null=True, upload_to='', verbose_name='Фото игрока')),
                ('Comments', models.TextField(verbose_name='Контракт с игроком')),
                ('Cost', models.PositiveSmallIntegerField(verbose_name='Стоимость контракта')),
                ('Opposing', models.CharField(max_length=64, verbose_name='Название команды противника')),
                ('CountryTeam', models.CharField(max_length=64, verbose_name='Страна команды противника')),
                ('TeamCoach', models.CharField(max_length=256, verbose_name='Тренер команды')),
                ('DateGame', models.DateField(verbose_name='Дата проведения игры')),
                ('Country', models.CharField(max_length=64, verbose_name='Страна проведения игры')),
                ('GameLevel', models.CharField(max_length=30, verbose_name='Уровень игры')),
                ('CountStart', models.PositiveSmallIntegerField(verbose_name='Количество забитых мячей')),
                ('CountFinish', models.PositiveSmallIntegerField(verbose_name='Количество пропущенных мячей')),
                ('Salary', models.PositiveSmallIntegerField(verbose_name='Премия игрока за игру')),
                ('Order', models.BooleanField(verbose_name='Участие в игре(да/нет)')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='Opposing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Opposing'),
        ),
    ]
