# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0003_auto_20170417_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labthree',
            options={'verbose_name': 'Запись о клубе', 'verbose_name_plural': 'Учёт футбольных клубов'},
        ),
        migrations.AlterField(
            model_name='labthree',
            name='Birthday',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='labthree',
            name='DateGame',
            field=models.DateTimeField(verbose_name='Дата проведения игры'),
        ),
        migrations.AlterField(
            model_name='labthree',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='Фото игрока'),
        ),
    ]
