# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0004_auto_20170419_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, null=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Таблица города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Таблица страны',
            },
        ),
        migrations.CreateModel(
            name='Do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.PositiveSmallIntegerField(verbose_name='Премия игрока за игру')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Таблица участие в игре',
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_type', models.CharField(max_length=64, null=True, verbose_name='Тип уровня')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Таблица уровней игры',
            },
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Запись о клубе', 'verbose_name_plural': 'Таблица клубы'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Лигу', 'verbose_name_plural': 'Таблица лиг'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Игру', 'verbose_name_plural': 'Таблица игры'},
        ),
        migrations.AlterModelOptions(
            name='opposing',
            options={'verbose_name': 'Команду противника', 'verbose_name_plural': 'Таблица команд противника'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрока', 'verbose_name_plural': 'Таблица игроков'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Положение', 'verbose_name_plural': 'Таблица положений в команде'},
        ),
        migrations.RemoveField(
            model_name='club',
            name='Head',
        ),
        migrations.RemoveField(
            model_name='club',
            name='Matches',
        ),
        migrations.RemoveField(
            model_name='club',
            name='Player',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Salary',
        ),
        migrations.RemoveField(
            model_name='opposing',
            name='Team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Contract',
        ),
        migrations.RemoveField(
            model_name='position',
            name='Type',
        ),
        migrations.AddField(
            model_name='club',
            name='Head_FIO',
            field=models.CharField(max_length=256, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='club',
            name='Head_number',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон руководителя'),
        ),
        migrations.AddField(
            model_name='match',
            name='Club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='opposing',
            name='Name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название команды противника'),
        ),
        migrations.AddField(
            model_name='player',
            name='Birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='player',
            name='Club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='player',
            name='Contract_comments',
            field=models.TextField(null=True, verbose_name='Условия контракта'),
        ),
        migrations.AddField(
            model_name='player',
            name='Contract_cost',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Стоимость контракта'),
        ),
        migrations.AddField(
            model_name='position',
            name='Name',
            field=models.CharField(max_length=20, null=True, verbose_name='Название положения'),
        ),
        migrations.AlterField(
            model_name='club',
            name='Base',
            field=models.CharField(max_length=64, verbose_name='Тренировочная база'),
        ),
        migrations.AlterField(
            model_name='club',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.City', verbose_name='Город размещения клуба'),
        ),
        migrations.AlterField(
            model_name='club',
            name='League',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.League', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='club',
            name='Name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название клуба'),
        ),
        migrations.AlterField(
            model_name='club',
            name='Year',
            field=models.PositiveSmallIntegerField(verbose_name='Год основания клуба'),
        ),
        migrations.AlterField(
            model_name='league',
            name='Name',
            field=models.CharField(max_length=64, verbose_name='Название лиги'),
        ),
        migrations.AlterField(
            model_name='match',
            name='CountFinish',
            field=models.PositiveIntegerField(verbose_name='Количество пропущенных мячей'),
        ),
        migrations.AlterField(
            model_name='match',
            name='CountStart',
            field=models.PositiveIntegerField(verbose_name='Количество забитых мячей'),
        ),
        migrations.AlterField(
            model_name='match',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Country', verbose_name='Страна проведения'),
        ),
        migrations.AlterField(
            model_name='match',
            name='Date',
            field=models.DateTimeField(verbose_name='Дата проведения игры'),
        ),
        migrations.AlterField(
            model_name='match',
            name='GameLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.GameLevel', verbose_name='Уровень игры'),
        ),
        migrations.AlterField(
            model_name='match',
            name='Opposing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Opposing', verbose_name='Команда противника'),
        ),
        migrations.AlterField(
            model_name='opposing',
            name='Coach',
            field=models.CharField(max_length=256, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='opposing',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Country', verbose_name='Страна команды противника'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Position', verbose_name='Положение игрока в команде'),
        ),
        migrations.AlterField(
            model_name='player',
            name='YearFact',
            field=models.PositiveSmallIntegerField(verbose_name='Принят в команду (год)'),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.AddField(
            model_name='do',
            name='Match_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Match', verbose_name='Код игры'),
        ),
        migrations.AddField(
            model_name='do',
            name='Player_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Player', verbose_name='Код игрока'),
        ),
    ]
