# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0006_auto_20170503_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Таблица игры'},
        ),
        migrations.RenameField(
            model_name='gamelevel',
            old_name='Level_type',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='match',
            name='CountFinish',
            field=models.PositiveIntegerField(verbose_name='К-во пропущенных мячей'),
        ),
        migrations.AlterField(
            model_name='match',
            name='CountStart',
            field=models.PositiveIntegerField(verbose_name='К-во забитых мячей'),
        ),
        migrations.AlterField(
            model_name='match',
            name='Date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
    ]
