# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0007_auto_20170503_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Opposing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Football.Opposing', verbose_name='Команда противника'),
        ),
    ]
