# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:05
from __future__ import unicode_literals

import Football.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0008_auto_20170522_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Year',
            field=models.PositiveSmallIntegerField(validators=[Football.models.validate_year], verbose_name='Год основания клуба'),
        ),
    ]
